version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: student-management-db-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: student_management
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-dev:/var/lib/mysql
      - ./setup_script.sh:/docker-entrypoint-initdb.d/setup_script.sh
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - student-network-dev

  # Backend Service
  backend:
    image: toktechteam/student-backend:latest
    container_name: student-management-backend-dev
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=student_management
      - PORT=3000
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - student-network-dev

  # Frontend Service
  frontend:
    image: toktechteam/student-frontend:latest
    container_name: student-management-frontend-dev
    restart: always
    ports:
      - "8080:8080"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - REACT_APP_ENV=development
    depends_on:
      - backend
    networks:
      - student-network-dev

volumes:
  mysql-data-dev:

networks:
  student-network-dev:
    driver: bridge