version: '3.8'

services:
  # Backend Service
  backend:
    image: toktechteam/student-backend:latest
    container_name: student-management-backend-qa
    restart: always
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=Root@123456
      - DB_NAME=student_management
      - PORT=3000
    network_mode: "host"

  # Frontend Service
  frontend:
    image: toktechteam/student-frontend:latest
    container_name: student-management-frontend-qa
    restart: always
    ports:
      - "8082:8080"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - REACT_APP_ENV=production
    depends_on:
      - backend
    network_mode: "host"