FROM node:16-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY backend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend code
COPY backend/*.js ./

# Expose the API port
EXPOSE 3000

# Start the backend server
CMD ["node", "server.js"]
