# Use Node.js as base image
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY backend/package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the application code
COPY backend ./

# Expose port that the app runs on
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]
